project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: LAMAMA
      - href: rr.qmd
        text: Générer un rapport R Markdown
      - href: r.qmd
        text: Exemple d'Analyse
      - href: exerciceR.qmd
        text: Exercices
      - href: apropos.qmd
        text: A propos

format:
  html:
    theme: journal
    css: styles.css
    toc: true



